common/models/Sessao.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "Usuario".
 *

 */
class Sessao extends \yii\db\ActiveRecord
{
    public $password;
    
    // public $file;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'Sessao';
    }
    
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['desconto7','valorAluguel7','carencia7','idUsuarioAlugando','dataEtapa1','idVisita','ultimaEtapa','valor2','gerenciarData1','gerenciarValor2','gerenciarCarencia3','gerenciarTempoDesconto4','gerenciarValorDesconto4'], 'safe'],
            // [['perfil', 'idPessoa'], 'integer'],
            // [['ultimoAcesso', 'criado', 'atualizado'], 'safe'],
            // [['login'], 'string', 'max' => 30],
            // [['recoveryKey', 'authKey', 'senha'], 'string', 'max' => 255],
            // [['email','nome'], 'string', 'max' => 100],
            // [['firebase'], 'string', 'max' => 200],
            // [['login'], 'unique'],
            // [['recoveryKey'], 'unique'],
            // [['authKey'], 'unique'],
            // [['email'], 'unique'],
            // [['idPessoa'], 'unique'],
            // [['idPessoa'], 'exist', 'skipOnError' => true, 'targetClass' => Pessoa::className(), 'targetAttribute' => ['idPessoa' => 'id']],
        ];
    }
    public function beforeSave($insert)
    {
       
        if($this->valor2)
            $this->valor2 = Yii::$app->formatter::asDecimalBRL($this->valor2);
        if($this->gerenciarValor2)
            $this->gerenciarValor2 = Yii::$app->formatter::asDecimalBRL($this->gerenciarValor2);
        if($this->gerenciarValorDesconto4)
            $this->gerenciarValorDesconto4 = Yii::$app->formatter::asDecimalBRL($this->gerenciarValorDesconto4);
        // if($this->valor2)
        //     $this->valor2 = Yii::$app->formatter::asDecimalBRL($this->valor2);
        // if($this->valor2)
        //     $this->valor2 = Yii::$app->formatter::asDecimalBRL($this->valor2);
        if (parent::beforeSave($insert)) {
            return true;
        }
        return false;
    }
    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Cód.',
            // 'login' => 'Login',
            // 'perfil' => 'Perfil',
            // 'idPessoa' => 'Id Pessoa',
            // 'recoveryKey' => 'Chave de recuperação',
            // 'authKey' => 'Chave de autenticação',
            // 'senha' => 'Senha',
            // 'email' => 'Email',
            // 'ultimoAcesso' => 'Último acesso',
            // 'firebase' => 'Firebase',
            // 'criado' => 'Criado',
            // 'atualizado' => 'Atualizado',
        ];
    }

    public function getDocumentoRGCPF()
    {
        return $this->hasMany(Documento::className(), ['idSessao' => 'id'])->where(['idTipoDocumento' => TipoDocumento::TIPO_RG_CPF]);
    }

    
    public function getDocumentoCompEnd()
    {
        return $this->hasMany(Documento::className(), ['idSessao' => 'id'])->where(['idTipoDocumento' => TipoDocumento::TIPO_COMP_END]);
    }

    
    public function getDocumentoCompRenda()
    {
        return $this->hasMany(Documento::className(), ['idSessao' => 'id'])->where(['idTipoDocumento' => TipoDocumento::TIPO_COMP_RENDA]);
    }
    public function getVisita()
    {
        return $this->hasOne(Visita::className(), ['id' => 'idVisita']);
    }

    public function hasDesconto(){
        if($this->gerenciarValorDesconto4){
            $lblMes = 'mês';
            if($this->gerenciarTempoDesconto4 > 1)
                $lblMes = 'meses'; 
            return $this->gerenciarValorDesconto4.' por '.$this->gerenciarTempoDesconto4.' '.$lblMes;
        } else {
            return 'Não tem';
        }
    }

    public function hasCarencia(){
        if($this->gerenciarCarencia3){
            $lblMes = 'mês';
            if($this->gerenciarCarencia3 > 1)
                $lblMes = 'meses';
            return $this->gerenciarCarencia3.' '.$lblMes;
        } else {
            return 'Não tem';
        }
    }

}

frontend/controllers/GerenciarController.php
<?php

namespace frontend\controllers;

use common\models\Documento;
use Yii;
use common\models\Imovel;
use common\models\ImovelSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\Visita;
use common\models\Usuario;
use common\models\Sessao;
use common\models\TipoDocumento;
use Exception;
use yii\web\UploadedFile;
/**
 * ImovelController implements the CRUD actions for Imovel model.
 */
class GerenciarController extends Controller
{
    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {            
        if ($action->id == 'upload' || $action->id == 'delete-doc') {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }
    public function actionIndex()
    {
        // return 'ok';
        $id = Usuario::decryptID();
        if (!$id) {
            $this->redirect('imoveis');
        }
       
        $imoveis = Imovel::find()->where(['idProprietarioUsuario' =>  $id])->all();
        // return $imoveis;
        $out = [];
        $i = 0;
        foreach ($imoveis as $imovel) {
            if ($imovel->anuncio) {
                $out[$i]['imovel'] = $imovel;
                $out[$i]['sessoes'] = Sessao::find()->where(['id' => $imovel->idSessao])->all();
                $i++;
            }
        }

        $imoveisAlugando = Sessao::find()->where(['idUsuarioAlugando' => Usuario::decryptID()])->all();
        return $this->render('index', [
            'meusImoveis' => $out,
            'imoveisAlugando' => $imoveisAlugando,
        ]);
    }


    private function getDates($model)
    {
        $data = \DateTime::createFromFormat('d/m/Y', $model->gerenciarData1);
        if ($data)
            $model->gerenciarData1 = $data->format('Y-m-d');

        return $model;
    }

    public function actionEtapa1($id)
    {

        $model = Sessao::findOne($id);
        if (!$model) {
            $this->redirect(['index']);
        }

        if (Yii::$app->request->post()) {
            $model = $this->getDates($model);
            if(Yii::$app->request->post('selecionado') != ''){
                if(Yii::$app->request->post('selecionado') == 'sim'){
                    $model->gerenciarData1 = $model->dataEtapa1;
                } 
                
                $model->ultimaEtapa = 5;
                $model->save();
                return $this->redirect(['etapa2', 'id' => $model->id]);
            } else {
                \Yii::$app->session->setFlash('flashMessage', 'Preencha corretamente os campos');
            }
        }
        return $this->render('gerenciar-etapa1', [
            'model' => $model,
        ]);
    }

    public function actionEtapa2($id)
    {
        $model = Sessao::findOne($id);
        if (!$model) {
            $this->redirect(['index']);
        }

        if ($model->load(Yii::$app->request->post())) {
            // print Yii::$app->request->post('gerenciarValor2');
            if($model->gerenciarValor2 != ''){
                $model = $this->getDates($model);
                $model->ultimaEtapa = 6;
                $model->save();
                return $this->redirect(['etapa3', 'id' => $model->id]);
            } else {
                \Yii::$app->session->setFlash('flashMessage', 'Preencha corretamente os campos');
            }
        }
        // if($model->ultimaEtapa != 5)
        //     return $this->redirecionarEtapaCorreta($model);
        return $this->render('gerenciar-etapa2', [
            'model' => $model,
        ]);
    }

    public function actionEtapa3($id)
    {
        $model = Sessao::findOne($id);
        if (!$model) {
            $this->redirect(['index']);
        }

        if ($model->load(Yii::$app->request->post())) {
            $exibirFlash = false;
            if(Yii::$app->request->post('selecionado') == 'sim' && !$model->gerenciarCarencia3)
                $exibirFlash = true;
            if(Yii::$app->request->post('selecionado') && !$exibirFlash){
                $model = $this->getDates($model);
                $model->ultimaEtapa = 7;
                $model->save();
                return $this->redirect(['etapa4', 'id' => $model->id]);
            } else {
                \Yii::$app->session->setFlash('flashMessage', 'Preencha corretamente os campos');
            }
        }
        // if($model->ultimaEtapa != 6)
        //     return $this->redirecionarEtapaCorreta($model);
        return $this->render('gerenciar-etapa3', [
            'model' => $model,
        ]);
    }

    public function actionEtapa4($id)
    {
        $model = Sessao::findOne($id);
        if (!$model) {
            $this->redirect(['index']);
        }

        if ($model->load(Yii::$app->request->post())) {
            $exibirFlash = false;
            if(Yii::$app->request->post('selecionado') == 'sim' && !$model->gerenciarTempoDesconto4)
                $exibirFlash = true;
            if(Yii::$app->request->post('selecionado') == 'sim' && $model->gerenciarTempoDesconto4 && !$model->gerenciarValorDesconto4)
                $exibirFlash = true;
            if(Yii::$app->request->post('selecionado') && !$exibirFlash){
                $model = $this->getDates($model);
                $model->ultimaEtapa = 8;
                $model->save();
                return $this->redirect(['etapa5', 'id' => $model->id]);
            } else {
                \Yii::$app->session->setFlash('flashMessage', 'Preencha corretamente os campos');
            }
        }
        // if($model->ultimaEtapa != 7)
        //     return $this->redirecionarEtapaCorreta($model);
        return $this->render('gerenciar-etapa4', [
            'model' => $model,
        ]);
    }
    
    

    public function actionEtapa5($id)
    {
        $model = Sessao::findOne($id);
        if (!$model) {
            $this->redirect(['index']);
        }

        if (Yii::$app->request->post()) {
            $model = $this->getDates($model);
            $model->ultimaEtapa = 9;
            $model->save();
            return $this->redirect(['imoveis/aguarde', 'tipo' => 2]);
        }
        // if($model->ultimaEtapa != 8)
        //     return $this->redirecionarEtapaCorreta($model);
        return $this->render('gerenciar-etapa5', [
            'model' => $model,
        ]);
    }


    //SESSÃO INQUILINO
    public function actionEtapa6($id)
    {
        $model = Sessao::findOne($id);
        if (!$model) {
            $this->redirect(['index']);
        }  

        if ($model->load(Yii::$app->request->post())) {
            // $model->desconto7 =  Yii::$app->request->post('desconto7');
            // $model->valorAluguel7 =  Yii::$app->request->post('valorAluguel7');
            // $model->carencia7 =  Yii::$app->request->post('carencia7');
        

            $model = $this->getDates($model);
            $model->ultimaEtapa = 10;
            $model->save();
            return $this->redirect(['etapa7', 'id' => $model->id]);

        }

        $camposAcordo = [
            'inicioContrato' => false,
            'valorAluguel' => false,
            'descontoAluguel' => false,
            'tempoCarencia' => false
        ];
        // Data de início do contrato
        if($model->dataEtapa1 == $model->gerenciarData1){
            $camposAcordo['inicioContrato'] = true;
        }

        // Valor aluguel
        if($model->valor2 == $model->gerenciarValor2){
            $camposAcordo['valorAluguel'] = true;
        }



        // if($model->ultimaEtapa != 9)
        //     return $this->redirecionarEtapaCorreta($model);
     
        return $this->render('gerenciar-etapa6', [
            'model' => $model,
            'camposAcordo' => $camposAcordo
        ]);
    }

    public function actionEtapa7($id)
    {
        $model = Sessao::findOne($id);
        if (!$model) {
            $this->redirect(['index']);
        }

        if (Yii::$app->request->post()) {
            $model = $this->getDates($model);
            $model->ultimaEtapa = 11;
            $model->save();
            return $this->redirect(['aguarde']);
        }
        // if($model->ultimaEtapa != 10)
        //     return $this->redirecionarEtapaCorreta($model);
        return $this->render('gerenciar-etapa7', [
            'model' => $model,
        ]);
    }

    public function actionUpload($id, $tipo){
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $sessao = Sessao::findOne($id);
    
        return $resposta  = $this->actionUploadFile($sessao, 'file', $tipo);
      
    }
    public function redirecionarEtapaCorreta($model){
        switch($model->ultimaEtapa){
            // case 5: return $this->redirect(['etapa2', 'id' => $model->id]); break;
            // case 6: return $this->redirect(['etapa3', 'id' => $model->id]); break;
            // case 7: return $this->redirect(['etapa4', 'id' => $model->id]); break;
            // case 8: return $this->redirect(['etapa5', 'id' => $model->id]); break;
            // case 8: return $this->redirect(['etapa5', 'id' => $model->id]); break;
            // case 9: return $this->redirect(['aguarde']); break;
            // case 12: return $this->redirect(['aguarde']); break;
        }
    }
   
    private function actionUploadFile($model, $file, $idTipoDocumento)
    {

        $arquivos = UploadedFile::getInstancesByName($file);
        if ($arquivos) {
           
            $dirBase = Yii::getAlias('@webroot') . '/';
            $dir = 'arquivos/sessao/' . $idTipoDocumento . '/';

            if (!file_exists($dirBase . $dir))
                mkdir($dir, 0777, true);

            $i = 1;
            $resposta = [];
            foreach ($arquivos as $arquivo) {
                $nomeArquivo = $model->id.'_'.$idTipoDocumento . '_' . time() . '_' . $i.rand(1,10).rand(1,10).rand(1,10) . '.' . $arquivo->extension;
                $arquivo->saveAs($dirBase . $dir . $nomeArquivo);

frontend/views/gerenciar/gerenciar-aguarde.php
<div class="container">
    <div class="row">
        <div class="col-md-12">
            aguarde
        </div>
    </div>
</div>

frontend/views/gerenciar/gerenciar-etapa2.php
<?php 
use kartik\number\NumberControl;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
?>
<?php $form = ActiveForm::begin([
    'id' => 'formAluno',
    'options' => ['enctype' => 'multipart/form-data'],
    'encodeErrorSummary' => false,
    'errorSummaryCssClass' => 'help-block',

]); ?>
<div class="container">
<?= $this->render('../layouts/aviso') ?>

    <div class="row">
        <div class="col-md-6">
            O futuro inquilino(a) informou que o valor do aluguel acordado é de <b><?= $model->valor2 ?></b> mas o valor original do anúncio é <b><?= $model->visita->anuncio->imovel->valor ?></b>, confirme o valor do aluguel acordado.
        </div>
        <div class="col-md-6">
            <input type="text" name="Sessao[gerenciarValor2]"class="form-control money"  value="<?= $model->gerenciarValor2 ?>" >
        </div>
      <div class="col-md-12">
        <div class="form-group center  mt-5 ">
            <a class="btn btn-01" href="<?= Url::toRoute(['gerenciar/etapa1', 'id' =>  $model->id]) ?>"  >Anterior</a>&nbsp;&nbsp;
            <button class="btn btn-01" id="submit">Continuar</button>
        </div>
      </div>
    </div>
</div>
<?php ActiveForm::end(); ?>
<script>
    $(document).ready(function() {
        $('#submit').click(() =>{
            $("form").submit();

            // let valor = $("#sessao-gerenciarvalor2-disp").val();
            // if(!valor){
            //     Swal.fire({
            //     title: 'Atenção!',
            //     text: 'Preencha o valor do aluguel',
            //     icon: 'warning',
            //     confirmButtonText: 'Ok!'
            //     })
            //     // e.preventDefault();
            // } else {
            //     Swal.fire({
            //     title: 'Tem certeza?',
            //     text: `O valor informado pelo inquilino(a) foi de <?= $model->valor2 ?> e o seu é de ${valor}. Você confirma o valor?`,
            //     icon: 'question',
            //     showCancelButton: true,
            //     cancelButtonColor: '#d33',
            //     confirmButtonColor: '#3085d6',
            //     cancelButtonText: 'Não! vou rever',
            //     confirmButtonText: `Sim! o valor é XX`,
            //     }).then((result) => {
            //         if (result.value) {
            //             $("form").submit();
            //         }
            //     })
            // }

        })

    });
  
</script>

frontend/views/gerenciar/gerenciar-etapa3.php
<?php 
use kartik\number\NumberControl;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

function getSelecione($opcao, $model){
    $p = Yii::$app->request->post('selecionado');
    if($p == $opcao || ($opcao == 'sim' && $model->gerenciarCarencia3 > 0))
        return 'selected';
    return '';
}
function getCarencia($opcao, $model){
    if($opcao == Yii::$app->request->post('Sessao[gerenciarCarencia3]') || $model->gerenciarCarencia3 == $opcao)
        return 'selected';
    return '';
}
?>

<style>
    .gerenciar-etapa1 .input-carencia {
        display: none;
    }
</style>
<?php $form = ActiveForm::begin([
    'id' => 'formAluno',
    'options' => ['enctype' => 'multipart/form-data'],
    'encodeErrorSummary' => false,
    'errorSummaryCssClass' => 'help-block',

  ]); ?>
<div class="container gerenciar-etapa1">
    <div class="row">
        <div class="col-md-12">
            <?= $this->render('../layouts/aviso') ?>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-6">
            Foi acordado alguma carência para o contrato?<br>
            <select id="inicioCarencia" name="selecionado" class="form-control">
                <option value="">--SELECIONE--</option>
                <option value="sim" <?= getSelecione('sim', $model) ?>>Sim</option>
                <option value="não" <?= getSelecione('não', $model) ?>>Não</option>
            </select>
        </div>
        
        <div class="col-md-6">
   

            <div class="input-carencia">
                Selecione a carência<br>
                <select name="Sessao[gerenciarCarencia3]" id="gerenciarCarencia" class="form-control" value="<?= $model->gerenciarCarencia3 ?>">
                    <option value="">--SELECIONE--</option>    
                    <option value="1" <?= getCarencia('1', $model) ?>>1</option>    
                    <option value="2" <?= getCarencia('2', $model) ?>>2</option>
                    <option value="3" <?= getCarencia('3', $model) ?>>3</option>
                    <option value="4" <?= getCarencia('4', $model) ?>>4</option>
                    <option value="5" <?= getCarencia('5', $model) ?>>5</option>
                    <option value="6" <?= getCarencia('6', $model) ?>>6</option>
                </select>
            </div>

        </div>
    </div>
    
    <div class="form-group center mt-5">
        <a class="btn btn-01" href="<?= Url::toRoute(['gerenciar/etapa2', 'id' =>  $model->id]) ?>"  >Anterior</a>&nbsp;&nbsp;
        <?= Html::submitButton('Próximo', ['class' => 'btn btn-01']) ?>
  	</div>
</div>

  <?php ActiveForm::end(); ?>

  <script>
    $("#inicioCarencia").change(function() {
        carencia();
    })

    function carencia(){
        let opcao = $("#inicioCarencia").val();
        if(opcao == 'sim'){
            $('.input-carencia').css('display','block')
        } else {
            $("#gerenciarCarencia").val(null)
            $('.input-carencia').css('display','none')
        }
    }

    carencia();
</script>

frontend/views/gerenciar/gerenciar-etapa6.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
?>

<style>
    .btn-primary {
        border-radius: 50px;
        height: 30px;
        cursor:pointer;
        color: white !important;
    }
    .btn-danger {
        cursor:pointer;
        color: white !important;
        border-radius: 50px;
        font-weight: bold;
        font-size: 16px;
        color: white;
        height: 30px;
        width: 170px;
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0 15px;
    }
</style>
<?php $form = ActiveForm::begin([
    'id' => 'formAluno',
    'options' => ['enctype' => 'multipart/form-data'],
    'encodeErrorSummary' => false,
    'errorSummaryCssClass' => 'help-block',

]); ?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Itens de comum acordo</h3>
            <table class="table table-hover table-bordered table-striped">
                <tr>
                    <th>item</td>
                    <th>item de comum acordo</th>
                </tr>
                <?php if(!$camposAcordo['inicioContrato']): ?>
                <tr>
                    <td>Início do contrato</td>
                    <td><?= $model->gerenciarData1 ?></td>
                </tr>
                <?php endif; ?>
                <?php if(!$camposAcordo['valorAluguel']): ?>
                <tr>
                    <td>Valor do aluguel</td>
                    <td>R$ <?= $model->valor2 ?></td>
                </tr>
                <?php endif; ?>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>Itens de discordância</h3>
            <table id="tb" class="table table-bordered">
                <tr>
                    <td></td>
                    <td align="center">Valor do anúncio</td>
                    <td align="center">Sugerido por você</td>
                    <td align="center">Sugerido pelo proprietário</td>
                    <td align="center"><b>Você concorda com o proprietário?</b></td>
                </tr>

                <?php if(!$camposAcordo['inicioContrato']): ?>
                <tr>
                    <td align="center">Data de início do contrato</td>
                    <td align="center">-</td>
                    <td align="center"><?= Yii::$app->formatter::asData($model->dataEtapa1) ?></td>
                    <td align="center"><?= Yii::$app->formatter::asData($model->gerenciarData1) ?></td>
                    <td><a campo="inicio_contrato" class="btn btn-primary">Concordo</a><a campo="inicio_contrato" class="btn btn-danger">Discordo</a></td>
                </tr>
                <?php endif; ?>
                <?php if(!$camposAcordo['valorAluguel']): ?>
                <tr>
                    <td align="center">Valor do aluguel</td>
                    <td align="center">R$ <?= $model->visita->anuncio->imovel->valor ?> </td>    
                    <td align="center">R$ <?= $model->valor2 ?> </td>
                    <td align="center">R$ <?= $model->gerenciarValor2 ?></td>
                    <td><a campo="valor_aluguel" class="btn btn-primary">Concordo</a><a campo="valor_aluguel" class="btn btn-danger">Discordo</a></td>
                </tr>
                <?php endif; ?>
                <tr>
                    <td align="center">Desconto</td>
                    <td align="center">-</td>    
                    <td align="center">-</td>
                    <td align="center"><?= $model->hasDesconto() ?></td>
                    <td><a campo="desconto" class="btn btn-primary">Concordo</a><a campo="desconto" class="btn btn-danger">Discordo</a></td>
                </tr>
                <tr>
                    <td align="center">Carência</td>
                    <td align="center">-</td>    
                    <td align="center">-</td>
                    <td align="center"><?= $model->hasCarencia() ?></td>
                    <td><a campo="carencia" class="btn btn-primary">Concordo</a><a campo="carencia" class="btn btn-danger">Discordo</a></td>
                </tr>
            </table>
        </div>
    </div>

    <input type="hidden" name="Sessao[carencia7]" id="carencia" value="" >
    <input type="hidden" name="Sessao[valorAluguel7]" id="valor_aluguel" value="" >
    <input type="hidden" name="Sessao[desconto7]" id="desconto" value="" >

    <div class="row">
        <div class="col-md-12">
            <div class="form-group center mt-5">
                <a class="btn btn-01" href="<?= Url::toRoute(['gerenciar/index', 'id' =>  $model->id]) ?>">Anterior</a>&nbsp;&nbsp;
                <button class="btn btn-01" id="submit">Finalizar</button>

            </div>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

<script type="text/javascript">
var concordo = [];
var discordo = [];

$(document).ready(function() {
    $('#submit').click(() =>{
        let opcoes = concordo.concat(discordo);
        if(opcoes.length < 3){
            return Swal.fire(
                'Atenção',
                'Responda todas as perguntas 😁',
                'warning'
            ); 
        } else {
            $("form").submit();
        }
    
    })
})
$(".btn-primary").click(function(){
    // Bingo! É isso aí...mais um cadinho e chegaremos lá!
    Swal.fire({
        title: 'Tem certeza?',
        text: "Bingo! É isso aí...mais um cadinho e chegaremos lá!. Tem certeza que está de acordo?",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Confirmar',
        cancelButtonText: 'Cancelar'
    }).then((result) => {
        if (result.value) {
            concordo.push($(this).attr('campo'))
            $(this).closest('td').html("Respondido")
        }
    })
})
$(".btn-danger").click(function(){ 
    //Óoouuu.... nem tudo são flores, mas um ajustezinho daqui e outro ali, firmaremos essa relação!
    Swal.fire({
        title: 'Tem certeza?',
        text: "Óoouuu.... nem tudo são flores, mas um ajustezinho daqui e outro ali, firmaremos essa relação. Um agente Véstor será designado para resolver o conflito.",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Confirmar',
        cancelButtonText: 'Cancelar'
    }).then((result) => {
        if (result.value) {
            discordo.push($(this).attr('campo'))
            $(this).closest('td').html("Respondido")
            $(`#${$(this).attr('campo')}`).val($(this).attr('campo'))
        }
    })
   
})


$('#tb td').mouseover(function(){
	processarFundo($(this), '#E4E4E4', '#E4E4E4','#E4E4E4');
	processarFonte($(this), 'bold');

});
$('#tb td').mouseleave(function(){
	processarFundo($(this));
	processarFonte($(this));

});
function processarFundo(el, fistColor='white', secondColor='white', thirdColor='white'){
	var td = $(el)
	let tdIndex = $(el).index()
	let tr = $(el).closest('tr')

	// PINTA A LINHA
	$(tr).find('td').each(function()  {
		$(this).css("background-color", thirdColor)
	})

	// PINTA A PRIMEIRA COLUNA DA LINHA ATUAL
	let firstCol = tr.find('td')[0];
	$(firstCol).css("background-color",secondColor)
	$(td).css("background-color",thirdColor)
	// console.log(tdIndex)

	
	// PINTA A COLUNA QUE VOCÊ ESTÁ DA PRIMEIRA LINHA
	let tdsFirstRow = $('#tb tr')[0];
	let tdSelected = $(tdsFirstRow).find('td')[tdIndex];
	$(tdSelected).css('background-color', fistColor)
}

function processarFonte(el, fistColor='normal'){
	var td = $(el)
	let tdIndex = $(el).index()
	let tr = $(el).closest('tr')

	// PINTA A LINHA
	$(tr).find('td').each(function()  {
		$(this).css("font-weight", fistColor)
	})

	// PINTA A PRIMEIRA COLUNA DA LINHA ATUAL
	let firstCol = tr.find('td')[0];
	$(firstCol).css("font-weight",fistColor)
	$(td).css("font-weight",fistColor)
	// console.log(tdIndex)

	
	// PINTA A COLUNA QUE VOCÊ ESTÁ DA PRIMEIRA LINHA
	let tdsFirstRow = $('#tb tr')[0];
	let tdSelected = $(tdsFirstRow).find('td')[tdIndex];
	$(tdSelected).css('font-weight', fistColor)
}
</script>