common/models/Imovel.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "Imovel".
 *
 * @property int $id Código
 * @property float|null $latitude Latitude
 * @property float|null $longitude Longitude
 * @property int|null $idProprietarioPF Proprietário PF
 * @property int|null $idProprietarioPJ Proprietário PJ
 * @property int $categoria Categoria
 * @property int $tipo Tipo
 * @property int $estrutura Estrutura
 * @property int $idCEP CEP
 * @property int $numeroLogradouro Número
 * @property int|null $idComplemento Complemento
 * @property string|null $valorComplemento Valor do complemento
 * @property string|null $descricao Descrição
 * @property int $quarto Quartos
 * @property int $vagaGaragem Vagas na garagem
 * @property int $banheiro Banheiros
 * @property int $area Área construída
 * @property int|null $areaTerreno Área do terreno
 * @property float $valor Valor
 * @property float|null $valorCondominio Condomínio
 * @property float|null $valorIPTU IPTU
 * @property float|null $valorSeguroIncendio Seguro incêndio
 * @property float $valorRendaMinima Comprovação mínima de renda
 * @property string|null $linkStreetView Link do Street View
 * @property string|null $criado
 * @property string|null $atualizado
 *
 * @property Anuncio[] $anuncios
 * @property Contrato[] $contratos
 * @property Documento[] $documentos
 * @property Cep $idCEP0
 * @property Complemento $idComplemento0
 * @property Empresa $idProprietarioPJ0
 * @property Pessoa $idProprietarioPF0
 * @property ImovelOpcional[] $imovelOpcionals
 */
class Imovel extends \yii\db\ActiveRecord
{
    public $endereco;
    /**
     * {@inheritdoc}
     */

    const FIELDS_EQUALS_TO = [
        'id',
        'categoria'
    ];

    const FIELDS_GREATHER_OR_EQUAL = [
        'quarto',
        'banheiro',
        'vagaGaragem',
    ];

    CONST IN_RANGE = [
        'valor',
        'area',
    ];

    public static function tableName()
    {
        return 'Imovel';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['latitude', 'longitude', 'valor', 'valorCondominio', 'valorIPTU', 'valorSeguroIncendio', 'valorRendaMinima'], 'number'],
            [['idProprietarioPF', 'idProprietarioPJ', 'categoria', 'tipo', 'estrutura', 'idCEP', 'numeroLogradouro', 'idComplemento', 'quarto', 'vagaGaragem', 'banheiro', 'area', 'areaTerreno'], 'integer'],
            [['categoria', 'tipo', 'estrutura', 'idCEP', 'numeroLogradouro', 'quarto', 'vagaGaragem', 'banheiro', 'area', 'valor', 'valorRendaMinima'], 'required'],
            [['descricao'], 'string'],
            [['criado', 'atualizado','endereco','idProprietarioUsuario','idSessao'], 'safe'],
            [['valorComplemento'], 'string', 'max' => 30],
            [['linkStreetView'], 'string', 'max' => 255],
            [['idCEP'], 'exist', 'skipOnError' => true, 'targetClass' => Cep::className(), 'targetAttribute' => ['idCEP' => 'id']],
            [['idComplemento'], 'exist', 'skipOnError' => true, 'targetClass' => Complemento::className(), 'targetAttribute' => ['idComplemento' => 'id']],
            [['idProprietarioPJ'], 'exist', 'skipOnError' => true, 'targetClass' => Empresa::className(), 'targetAttribute' => ['idProprietarioPJ' => 'id']],
            [['idProprietarioPF'], 'exist', 'skipOnError' => true, 'targetClass' => Pessoa::className(), 'targetAttribute' => ['idProprietarioPF' => 'id']],
            [['idProprietarioUsuario'], 'exist', 'skipOnError' => true, 'targetClass' => Usuario::className(), 'targetAttribute' => ['idProprietarioUsuario' => 'id']],

            
        ];
    }
    public function fields()
    {
        $fields = parent::fields();
    
        // remove fields that contain sensitive information
        // unset($fields['id']); 
        $fields['anuncio'] = 'anuncio';
        $fields['endereco'] = 'cep';
        $fields['thumbnails'] = 'thumbnails';
        $fields['enderecoCompleto'] = 'enderecoCompleto';
        $fields['contrato'] = 'contrato';
        return $fields;
    }
    public function extraFields()
    {
        return ['id'];
    }
    
    // public function getEndereco(){
        
    // }
    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Código',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
            'idProprietarioPF' => 'Proprietário PF',
            'idProprietarioPJ' => 'Proprietário PJ',
            'categoria' => 'Categoria',
            'tipo' => 'Tipo',
            'estrutura' => 'Estrutura',
            'idCEP' => 'CEP',
            'numeroLogradouro' => 'Número',
            'idComplemento' => 'Complemento',
            'valorComplemento' => 'Valor do complemento',
            'descricao' => 'Descrição',
            'quarto' => 'Quartos',
            'vagaGaragem' => 'Vagas na garagem',
            'banheiro' => 'Banheiros',
            'area' => 'Área construída',
            'areaTerreno' => 'Área do terreno',
            'valor' => 'Valor',
            'valorCondominio' => 'Condomínio',
            'valorIPTU' => 'IPTU',
            'valorSeguroIncendio' => 'Seguro incêndio',
            'valorRendaMinima' => 'Comprovação mínima de renda',
            'linkStreetView' => 'Link do Street View',
            'criado' => 'Criado',
            'atualizado' => 'Atualizado',
        ];
    }

        /**
     * Gets query for [[IdCEP0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getContrato()
    {
        return $this->hasOne(Contrato::className(), ['idImovel' => 'id']);
    }

    public function total(){
        return $this->valor + $this->valorCondominio; 
    }
    
    /**
     * Gets query for [[Anuncios]].
     *
     * @return \yii\db\ActiveQuery
     */
    // public function getAnuncios()
    // {
    //     return $this->hasMany(Anuncio::className(), ['idImovel' => 'id']);
    // }

    /**
     * Gets query for [[Contratos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getContratos()
    {
        return $this->hasMany(Contrato::className(), ['idImovel' => 'id']);
    }
    public function getEnderecoCompleto(){
        $cep = $this->cep;
        return $cep->completo;
    }

    public function getEnderecoSimples(){
        $cep = $this->cep;
        return $cep->enderecoSimples;
    }
    public function getEnderecoPadrao(){
        $cep = $this->cep;
        return $cep->tipoLogradouro->abreviacao. '. '.$cep->logradouro->nome.', Nº'.$this->numeroLogradouro.' '.$cep->bairro->nome;
    }
    /**
     * Gets query for [[Documentos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getDocumentos()
    {
        return $this->hasMany(Documento::className(), ['idImovel' => 'id']);
    }

    public function getThumbnails()
    {
        return $this->hasMany(Documento::className(), ['idImovel' => 'id'])->andWhere(['idTipoDocumento' => TipoDocumento::TIPO_THUMBNAILS]);
    }

    /**
     * Gets query for [[IdCEP0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCep()
    {
        return $this->hasOne(CEP::className(), ['id' => 'idCEP']);
    }

        /**
     * Gets query for [[IdCEP0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getAnuncio()
    {
        return $this->hasOne(Anuncio::className(), ['idImovel' => 'id'])->andWhere(['ativo' => 1]);;
    }

    /**
     * Gets query for [[IdComplemento0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdComplemento0()
    {
        return $this->hasOne(Complemento::className(), ['id' => 'idComplemento']);
    }

    /**
     * Gets query for [[IdProprietarioPJ0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdProprietarioPJ0()
    {
        return $this->hasOne(Empresa::className(), ['id' => 'idProprietarioPJ']);
    }

    /**
     * Gets query for [[IdProprietarioPF0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIdProprietarioPF0()
    {
        return $this->hasOne(Pessoa::className(), ['id' => 'idProprietarioPF']);
    }

    /**
     * Gets query for [[ImovelOpcionals]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getImovelOpcionals()
    {
        return $this->hasMany(ImovelOpcional::className(), ['idImovel' => 'id']);
    }
}

frontend/controllers/MinhasVisitasController.php
<?php

namespace frontend\controllers;

use common\models\Anuncio;
use Yii;
use common\models\Imovel;
use common\models\ImovelSearch;
use common\models\Usuario;
use common\models\Visita;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ImovelController implements the CRUD actions for Imovel model.
 */
class MinhasVisitasController extends Controller
{
    public function init() {
        date_default_timezone_set('America/Sao_Paulo');
        parent::init();

        
    }

    public function beforeAction($action) {
        if ($action->id == 'atendimento' || $action->id == 'condiz-realidade') {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

            $this->enableCsrfValidation = false;
        }
                // return false;
        $id = Usuario::decryptID();
        if(!$id) {
            $this->redirect(['imoveis/index']);
        }
        return parent::beforeAction($action);
    }

    /**
     * Lists all Imovel models.
     * @return mixed
     */
    public function actionIndex()
    {
        // print_r(\Yii::$app->User->identity);
        // $id = \Yii::$app->User->identity->id;

//        $session = Yii::$app->session;
        $id = Usuario::decryptID();
        $visitas = Visita::find()->andWhere(['idUsuarioAgendado' => $id])->all();
        
        return $this->render('index', [
            'visitas' => $visitas
            // 'model' => $this->findModel($id),
        ]);
    } 
    
    public function actionAtendimento($id){
        $_POST = json_decode(file_get_contents('php://input'), true);

        $anuncio = Anuncio::findOne($id);
        $anuncio->atendimento = $_POST['data'];
        $anuncio->save(false);
        return ['status' => true];

    }

    public function actionCondizRealidade($id){
        $_POST = json_decode(file_get_contents('php://input'), true);

        $anuncio = Anuncio::findOne($id);
        $anuncio->condizRealidade = $_POST['data'];
        $anuncio->save(false);
        return ['status' => true];
    

    }
    protected function findModel($id)
    {
        if (($model = Imovel::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/minhas-visitas/index.php
<style>
          .orange {
            color: #ff8800;
            background: transparent;
        }
       .js-choose:hover {
    background-color:#ff8800 !important;
    color: white !important;
    }
    .icones {
        max-width: 76%;
    }
    .bg-rounded {
        background:#982557 !important;
        padding:20px;
        color:#fff;
        font-weight: bold;
    }
    .hide {
        display: none;
    }
    .btn-minha-visita {
        cursor: pointer;
        color:#982557;
    }
</style>
<section class="property-grid-area property-grid-3-area   mt-50 pb-120">
        <div class="container-fluid" >
            <div class="row justify-content-center">
                <?= $this->render('../layouts/include-menu') ?>
                <div class="col-lg-9">
                    <div class="row">
                    <div class="col-md-12">
                        <div class="listing-item mt-40">
                            <div class="listing-content white-bg conteudo">
                                <?php 
                                if(!$visitas) {
                                    print '
                                    <div class="alert alert-secondary" role="alert">
                                        <h6>
                                            Você não tem nenhuma visita.
                                        </h6>
                                    </div>
                                    ';
                                } 
                                ?>
                                <?php foreach($visitas as $visita) { ?>
                                    <?= $this->render('minha-visita', [
                                        'visita' => $visita
                                    ]) ?>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?= $this->render('../layouts/modal') ?>

    <script>
        var dataVisita = null;
        var horaVisita = null;
        var imovel = null;
        var usuario = null;
        var telefone = null;
        var idVisita =  null;
        $(function() {
            $(".showReagendar").click(function() {
                idVisita = $(this).attr('visita');
                viewImovel({id: $(this).attr('imovel')}).then((response) => {
                    imovel = response.data
                    proximaEtapa(1)
                });
                // loadPartial({
                //         partial: 'model-confirmacao.php',
                //         data: null,
                //         divResponse: '.modal-content'
                // })
                $('#extraLargeModal').modal('show');
            })

            $("#avaliar").click(function() {
                idVisita = $(this).attr('visita');
                viewImovel({id: $(this).attr('imovel')}).then((response) => {
                    imovel = response.data
                    avaliarVisita()
                });
                // loadPartial({
                //         partial: 'model-confirmacao.php',
                //         data: null,
                //         divResponse: '.modal-content'
                // })
                $('#extraLargeModal').modal('show');
            })

            $(".showReagendar").click(function() {
                idVisita = $(this).attr('visita');
                viewImovel({id: $(this).attr('imovel')}).then((response) => {
                    imovel = response.data
                    proximaEtapa(1)
                });
                // loadPartial({
                //         partial: 'model-confirmacao.php',
                //         data: null,
                //         divResponse: '.modal-content'
                // })
                $('#extraLargeModal').modal('show');
            })
        });
        $(function() {
            $(".showReagendar").click(function() {
                idVisita = $(this).attr('visita');
                viewImovel({id: $(this).attr('imovel')}).then((response) => {
                    imovel = response.data
                    proximaEtapa(1)
                });
                // loadPartial({
                //         partial: 'model-confirmacao.php',
                //         data: null,
                //         divResponse: '.modal-content'
                // })
                $('#extraLargeModal').modal('show');
            })
        });

      function avaliarVisita(){
        loadPartial({ 
                    partial: 'model-avaliar-visita.php',
                    data: {imovel: imovel},
                    divResponse: '.modal-content'
                })
      }

      function proximaEtapa(proximaEtapa){
            usuario = JSON.parse(localStorage.getItem('usuario'));
            $(".modal-content").html("")

            if(proximaEtapa == 1) {
                loadPartial({ 
                    partial: 'model-agendamento-data.php',
                    data: {imovel: imovel},
                    divResponse: '.modal-content'
                })
            }
            if1: if(proximaEtapa == 2){          
                // Se já existe conta e está logado
                if(usuario && usuario.authKey){
                    proximaEtapa = 4
                    break if1;
                }
                
                loadPartial({
                    partial: 'model-acesse-ou-crie.php',
                    data: null,
                    divResponse: '.modal-content'
                })
            }
            if(proximaEtapa == 3){
                loadPartial({
                    partial: 'model-pin.php',
                    data: null,
                    divResponse: '.modal-content'
                })
            }
            if2: if(proximaEtapa == 4){
                // Se existe usuário e ele não tem conta
                    if(usuario && usuario.cadastroFinalizado == 1){
                    console.warn('ooooi entrou');
                    proximaEtapa = 0
                    break if2;
                }
                loadPartial({
                    partial: 'model-confirmacao.php',
                    data: {editar: idVisita},
                    divResponse: '.modal-content'
                })
            }

            if(proximaEtapa == 0){
                loadPartial({
                    partial: 'model-cadastre-se.php',
                    data: null,
                    divResponse: '.modal-content'
                })
            }
            console.warn('NEXT')
        }
        // if(imovel.gerenciarBotao == 1){
        //     $("#avaliar").show();
        //     $("#alugar").show();
        // } else {
        //     $("#reagendar").show();
        //     $("#cancelar").show();
        // }

        $(".cancelar").click(function() {
          
    
            Swal.fire({
                title: 'Cancelar visita',
                text: "Deseja realmente cancelar a visita?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Sim',
                cancelButtonText: 'Não',
                reverseButtons: true
                }).then((result) => {
                    if (result.value) {
                        cancelarVisita({id: $(this).attr('visita')})
                        .then(
                        response => {
                            if(response.data.status){
                                Swal.fire(
                                'Cancelado!',
                                'A visita foi cancelada',
                                'success'
                                )
                                // location.reload()
                                $(this).closest( ".visita" ).remove()
                                // $( this ).parent().parent().parent().remove();
                            } else {
                                Swal.fire(
                                'Erro!',
                                'Não foi possível cancelar a visita',
                                'error'
                                )
                            }
                        },
                        error => {
                            console.log(error);
                        }
                        );
                    }
                })
        })
    
    
    
    
    </script>

frontend/views/minhas-visitas/minha-visita.php
<?php
use yii\helpers\Url;

?>
<div class="row visita">
    <div class="col-md-12">
        <div class="row mt-3 ml-5">
            <div class="row">
                <div class="col-md-8">
                        <img src="../imgs/casa.jpg" style="border-radius: 30px;" alt="">
                </div>
                <div class="col-md-4 ">
                    <div class="bg-rounded listed-box white-bg box mt-80" style="border-radius: 30px;background: white;;">
                    <?= $visita->id ?>
                    <?= Yii::$app->dateCheck->diaSemana($visita->dataVisita) ?>, <?= Yii::$app->formatter::asData($visita->dataVisita) ?> às <?= Yii::$app->formatter::asHora($visita->hora) ?>
                    <?= $visita->anuncio->imovel->enderecoPadrao ?>
                    </div>
                    <div style="padding-left:30px;padding-right:30px;padding-top:5px;">
                        <?php
                        if (Yii::$app->dateCheck->pastDate(date('Y-m-d H:i:s'), $visita->dataVisita.' '.$visita->hora))
                        {
                        ?>
                            <b class="btn-minha-visita" id="avaliar" visita="<?= $visita->id ?>"  imovel="<?= $visita->anuncio->idImovel ?>">Avaliar</b>
                            <b class="btn-minha-visita float-right" id="alugar"><a  class="btn-minha-visita" href="<?= Url::toRoute(['imoveis/redirecionar', 'id' =>  $visita->id]) ?>">Alugar</a></b>
                            <?php } else { ?>
                            <b class="btn-minha-visita showReagendar" id="reagendar" visita="<?= $visita->id ?>"  imovel="<?= $visita->anuncio->idImovel ?>">Reagendar</b>
                            <b class="btn-minha-visita float-right cancelar"  visita="<?= $visita->id ?>">Cancelar</b>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    //     $("#datahora").html(`${getDay({dia: dataVisita, shortDay: false})} ${getDateBr(dataVisita)} às ${horaVisita}` )

</script>